/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#00354c",
        "primary-container": "#004d6c",
        "on-primary": "#ffffff",
        "on-primary-container": "#85bde1",
        "primary-fixed": "#c6e7ff",
        "primary-fixed-dim": "#96cdf2",
        "on-primary-fixed": "#001e2d",
        "on-primary-fixed-variant": "#004c6b",
        "inverse-primary": "#96cdf2",

        "secondary": "#006876",
        "secondary-container": "#92edff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#006d7b",
        "secondary-fixed": "#9eefff",
        "secondary-fixed-dim": "#77d4e5",
        "on-secondary-fixed": "#001f24",
        "on-secondary-fixed-variant": "#004e59",

        "tertiary": "#003831",
        "tertiary-container": "#005147",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#81c2b5",
        "tertiary-fixed": "#adefe1",
        "tertiary-fixed-dim": "#91d3c6",
        "on-tertiary-fixed": "#00201c",
        "on-tertiary-fixed-variant": "#005047",

        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",

        "surface": "#f7f9fd",
        "surface-bright": "#f8f9fd",
        "surface-dim": "#d8dade",
        "surface-variant": "#e0e3e6",
        "surface-tint": "#03658c",
        "on-surface": "#191c1f",
        "on-surface-variant": "#41484d",
        "inverse-surface": "#2d3134",
        "inverse-on-surface": "#eff1f4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3f8",
        "surface-container": "#eceef2",
        "surface-container-high": "#e7e8ec",
        "surface-container-highest": "#e0e3e6",

        "outline": "#70787f",
        "outline-variant": "#bfc7cf",
        "background": "#f8f9fd",
        "on-background": "#191c1f",

        "lavender": "#f0f0fe",
        "lavender-dark": "#4338ca",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.125rem",
        "md": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px",
      },
      spacing: {
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "grid-gutter": "1.5rem",
        "grid-margin": "2rem",
      },
      fontFamily: {
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "headline-xl-mobile": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-sm": ["10px", { lineHeight: "14px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
